### ISSUE TITLE
[discussion] fix `-g` and `-level`?

### ISSUE THREAD

**Issue by retokromer** [MediaArea/RAWcooked#102]
- Does it make any sense to allow other values than `-g 1`?
- Does it make any sense to allow other values than `-level 3`?

I personally don’t see and therefore I suggest to delete the possibility to change those values.

**Comment by JeromeMartinez** [comment]
> Does it make any sense to allow other values than `-g 1`?

I am aware that lot of people like Intra compression, but my of view is that I prefer, for the same total cost, store 3 times a Non-Intra file in 3 different physical locations rather than twice an Intra file in 2 different physical locations. I'll provide a demonstration with numbers about the reason (risk management) later.

> Does it make any sense to allow other values than `-level 3`?

I don't plan to use it, but some people may want to use a version of FFV1 more compatible with older players. Additionally, this option will be later useful when FFV1 v4 is out (someone who does not want to use v4 when RAWcooked switches to v4 by default can put today the wanted version  in the scripts).

***

As as a general note, I prefer to not be the judge of which option is good or bad, and I prefer to permit the user to judge, so I prefer to permit all options permitted by the encoder (when such option does not prevent reversibility).

**Comment by retokromer** [comment]
These are not rhetoric questions, but of the utility of permitting FFV1 version 0 and 1 came up [this morning](https://reto.ch/training/2018/20180608.html), as well as the question of permitting other GOP sizes. And I could not give an argument for…

**Comment by retokromer** [comment]
P.S. – With `-level 0` and `-level 1` it crashes:

[ffv1 @ 0x7ffa05008c00] Version 3 needed for requested features but 0 requested
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

**Comment by JeromeMartinez** [comment]
"I could not give an argument for" this is the case for most tools actually: people knowing the meaning of all options of a tool like FFmpeg are rare (or... don't exist).
And I provided arguments in my first answer, easy now ;-).

Again, the tool is not for only 1 person, so other persons may have different opinions, 1 person not willing to use it or not knowing the usage is not a reason IMO for removing an option.
Such option exists in FFmpeg, so someone imagined an interest for them, and I don't want to be the judge about them.

**Comment by retokromer** [comment]
>Again, the tool is not for only 1 person, so other persons may have different opinions, 1 person not willing to use it or not knowing the usage is not a reason IMO for removing an option.

Because it’s before RGB48 has been implemented.

**Comment by JeromeMartinez** [comment]
> P.S. – With -level 0 and -level 1 it crashes:

Please 1 ticket per issue, else it is difficult to track discussions.

**Comment by retokromer** [comment]
Please 1 ticket per issue, else it is difficult to track discussions.

**Comment by retokromer** [comment]
I disagree about the utility to allow FFV1 version 0 and 1 in RAWcooked and I’ve suggested to allow «only» from version 3 on. Yet this is not blocking at all, therefore closing.
