### ISSUE TITLE
Conversion failed when using `-level 0`

### ISSUE THREAD

**Issue by retokromer** [MediaArea/RAWcooked#103]
When using the option `-level 0` on regular RGB48 content, I receive an error:

<img width="888" alt="bildschirmfoto 2018-06-08 um 17 44 24" src="https://user-images.githubusercontent.com/3246607/41167595-ae6bf0ac-6b43-11e8-99f8-89162c696272.png">

**Comment by JeromeMartinez** [comment]
I see, I force "defaults" for all levels, but e.g. slicecrc is available only from v3. Will not force unsupported features when a level not supporting the feature is requested.

**Comment by JeromeMartinez** [comment]
Workaround: ` -level 0 -slicecrc 0 -slices 1`

**Comment by retokromer** [comment]
Hmm… `-slicecrc 0` ;-)

**Comment by JeromeMartinez** [comment]
You try `-level 0` so... normal ;-)

**Comment by JeromeMartinez** [comment]
Thinking more about the issue, using levels 0 & 1 remove features, and these removed features (slices) are useful for RAWcooked. So I move on providing a message `" -level 0" does not permit slices, is it intended? if so, add " -slices 1" to the command` instead of removing automatically the support of slices when " -level 0" is provided.

Note: hesitating about doing same for " -slicecrc", as actually [FFmpeg can add CRC in version 0/1 of FFV1](https://github.com/FFmpeg/FFV1/pull/112/files) (and RAWcooked, as well as MediaConch, read them), even if it is not standard.
