### ISSUE TITLE
[wish] choose encoder

### ISSUE THREAD

**Issue by retokromer** [MediaArea/RAWcooked#23]
I suggest to add a flag to the CLI `rawcooked`, allowing to choose a specific encoder or decoder to use:

- the future internal one
- FFmpeg’s one (currently used)
- another one

**Comment by JeromeMartinez** [comment]
for the decoder, it would not be "lossless" (about the metadata, DPX flavor...), you want the corresponding command line anyway?

My idea was more about the encoder only.

**Comment by retokromer** [comment]
Hmm… You are perfectly right: the encoder only!

**Comment by retokromer** [comment]
I played a little, and I come to the conclusion that to offer the possibility to modify both the encoder and the decoder is the better solution. Therefore, I suggest to give to the user the possibility to define an alternate encoder and/or decoder. If none is specified, then – of course – the internal ones are used.

**Comment by JeromeMartinez** [comment]
There is no plan to remove the FFmpeg encoding possibility, no problem.

**Comment by retokromer** [comment]
After more intensive tests of the current alpha, I guess my original idea to give the possibility to chose both the encoder and the decoder is the better one.

FYI @JeromeMartinez: I will start tomorrow a stress test over some TB and compare the new figures with the ones from beginning of February (which I skipped from my presentation in Prague).

**Comment by JeromeMartinez** [comment]
> After more intensive tests of the current alpha, I guess my original idea to give the possibility to chose both the encoder and the decoder is the better one.

Is it acceptable if I release the v1 with only FFmpeg encoder? From debate on CELLAR mailing list, having Matroska element dedicated to RAWcooked is not appreciated, and an attachment (current method) is preferred, so internal encoder is less needed (I don't mean I won't do it, I still want to do it because I think I can have better performances, but reducing the scope of v1 may speed up the release).

> I will start tomorrow a stress test

I plan to merge https://github.com/MediaArea/RAWcooked/pull/49 today, so you could test by pointing the directory only. Or do you have packages with more than 1 subdirectory (DPX spanned other several directories)?

**Comment by pjotrek-b** [comment]
@JeromeMartinez: You mention above, that "_for the decoder, it would not be "lossless" (about the metadata, DPX flavor...)_"

Would this still be the case, even if the internal decoder also uses the rawcooked-attachment data (instead of a dedicated matroska element)?
Do I understand this correctly?

**Comment by retokromer** [comment]
What is the status of this?

**Comment by JeromeMartinez** [comment]
On my side it is blocked because I don't have any other encoder for testing, or at least the expected options to support.
Without details about what is expected by the other encoder, impossible to implement this wish.

Right now binary location can be changed so the other encoder can be selected if it has the same interface (same options), so either the other encoder you think about has the same options and the wish is fulfilled, or the other encoder you think about has different options and the wish can not be fulfilled without details about the expected options.

**Comment by retokromer** [comment]
In my opinion, RAWcooked should «just» pass all the parameters to the other encoder and it’s up to it how to deal with.

**Comment by JeromeMartinez** [comment]
How do I know the option for providing the attached file if I don't know the corresponding option?
I could add an option for authorizing any option instead of default validation of only the options I tested, it does not remove the issue about knowing how to set up the other encoder with the paths and sequence method for the DPX files, and reversibility would not be guaranteed.

Note that if you want only the reversibility file and create yourself the exact command, you can use `--display-command` and ignore the result (except for getting the reversibility file name).

Please provide an example about the workflow you expect, I don't understand your idea in practice (it seems just impossible).
e.g. how should I do if "-i" of FFmpeg is "-blabla" on your encoder? what do you expect as RAWcooked input and as RAWcooked output.

**Comment by retokromer** [comment]
I’m speaking about the video part: the encoding to and decoding from FFV1, because it can be done better (in terms of both execution speed and compression rate) than by the current FFmpeg implementation. I guess this is the same goal as your own coder.

**Comment by JeromeMartinez** [comment]
> I’m speaking about the video part

How do I know that an option is "video part"?
What is video part? FFmpeg -vframes is video part but breaks reversibility.

If I understand well, you don't want to permit another encoder with different interface (e.g `-c:v ffv1` stays as is with your own encoder interface) but you want to permit any option (even ones that break reversibility), I can add an option for permitting any option on the command line (with a big warning "reversibility not guaranteed", use such option at your own risks)

> I guess this is the same goal as your own coder.

my own encoder would take the interface from FFmpeg, so has no issue there.

***

Again, please provide an example of what you want to get as input then output, I don't understand what you expect. the "choose encoder" wish is by my interpretation being able to support the interface of another encoder i.e knowing the right commands for getting a reversible file, looks like we are not in sync about the idea behind this ticket.

**Comment by JeromeMartinez** [comment]
> I guess this is the same goal as your own coder.

For clarification, the possibilities I see: 
- if it is internal to RAWcooked, I will know how to configure the the code for launching it as I code it, I'll have all I need. Blocked up to the availability of the internal encoder.
- if it is an addition to FFmpeg (alternate FFV1 encoder, let call it "superfastffv1"), I'll test the integration then authorize " -c:v superfastffv1" option. Blocked up to the availability of the encoder in FFmpeg.
- if someone wants me to authorize "superfastffv1" encoder in FFmpeg without having me test that reversibility is fine, I can add an option for authorizing untested options. Blocked until the wish is explicitly this one then quick to add.
- if someone wants me to support another encoder/muxer (not like FFmpeg command line), I need at least documentation about the interface for knowing how to set up input streams and attachments. Blocked until documentation is provided.
- if something else, blocked until I have more details.

**Comment by retokromer** [comment]
I guess, we are almost in sync.

In theory I would like to be able to use any coder. In practice I’m thinking about FFV1 (FFmpeg’s `-c:v ffv1` or your `-c:v ffv1_media` or mine `-c:v ffv1_reto`) and HuffYUV (`-c:v ffvhuff`).

**Comment by retokromer** [comment]
P.S. – I guess I found which part of the code I should modify. If I have time, I will give a try during the weekend and open a PR.

**Comment by JeromeMartinez** [comment]
> HuffYUV (`-c:v ffvhuff`).

Exactly what I am afraid about.
If RAWcooked is not adapted for supporting this format (not FFV1), reversibility is not possible. This is the reason I am reluctant to let the user enter any name without a big warning "reversibility not guaranted".

> mine `-c:v ffv1_reto`

if this encoder has same interface (slices...), it is quick (just authorize `-c:v ffv1_reto`), if this encoder supports no options it is a bit longer (options need to be rejected), if this encoder support different options it is a bit longer too (filter the authorized options), and I am missing the encoder name and the list of options to authorize, main reason the issue was stalled for "another one" part of the issue.

Note that due to unavailability (for me) of the encoder, no test will be done, you will be responsibility of the reversibility.

**Comment by retokromer** [comment]
Of course, if the standard coder is not used, then it’s not RAWcooked’s responsibility! Yet why not let the possibility open to use another coder? That’s my **_only_** point.

**Comment by JeromeMartinez** [comment]
> Yet why not let the possibility open to use another coder? That’s my **_only_** point.

The indicated wish was to be able to choose another encoder. It was not said that it is to permit to break the promise of reversibility.
Goal of RAWcooked is to permit reversibility, and letting the possibility open may break this promise, it is a dangerous option.

Here you don't ask me anymore to support another encoder (so with tests, for being sure it is fine), but to permit the user to provide options potentially breaking the promise of reversability, totally different request and I didn't understand that you want me to jut permit options without testing them.

I am fine for adding the possibility to let the user decides of using untested option, but in that case with a big warning in the doc (help...) that reversibility is not guaranteed.

I would not a agree to just accept any `-c:v` name as it makes the user believes that the option has be tested by us and that we guarantee that reversibility is fine.
I suggest something like `--nowarranty` option for permitting any option (so including `-c:v`).
maybe  `-c:v ffv1_reto` could be an exception, and in the doc we say that support is not provided by MediaArea but by Reto.

**Comment by retokromer** [comment]
I suggest to let as it is (which let’s me unhappy, but I know how to circumvent ;-)

**Comment by retokromer** [comment]
Should I then close the issue?

**Comment by JeromeMartinez** [comment]
As you suggest to let it as is after discussion instead of deciding of something needing some development, I guess so.

On my side, I'll add the option for choosing another encoder when another encoder is publicly available (the issue or PR name will be "support of encoder X").
