### ISSUE TITLE
Library not loaded/image not found

### ISSUE THREAD

**Issue by jimhone** [MediaArea/RAWcooked#275]
After recently upgrading ffmpeg, I just started to receive this error when trying to run RAWcooked. 

Track 1:                      les/s    
  eyes2018JacksonR2_%08d.dpx
 (00086400 --> 00118031)
  DPX/Raw/RGB/10bit/FilledA/BE

dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/bin/ffmpeg
  Reason: image not found

I'm trying to figure out what I've done wrong.
Thanks!

**Comment by JeromeMartinez** [comment]
> dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib

Looks like something independent from RAWcooked.
Please test FFmpeg alone, e.g. `ffmpeg  -f lavfi -i testsrc -t 1 -f null -` (it creates a fake stream and send it to nowhere).
If you get the same error, that demonstrates that the issue is not in RAWcooked, and in that case the issue should be reported to the person who provided to you this FFmpeg package (which is weird: installed in /usr/local/bin, with a link to /usr/local/opt, it seems a very custom version; I would advise to remove it completely and reinstall the version provided by your distro).

**Comment by jimhone** [comment]
Jerome,

I ran the test, and you were correct.  It was a bad installation of FFmpeg.  
I removed it, then reinstalled it with Reto Kromer's instructions. RAWcooked is now running without any problems.

Thanks!

**Comment by retokromer** [comment]
@jimhone Probably you updated `libssl` (possibly via another piece of software). Then `ffmpeg` needs to be reinstalled. Glad the instructions were helpful.

**Comment by retokromer** [comment]
Can this one be closed?

**Comment by jimhone** [comment]
Yes. Thanks for your help!
