### ISSUE TITLE
Warning: non-conforming DPX Total image file size (x17694)

### ISSUE THREAD

**Issue by archisysio** [MediaArea/RAWcooked#341]
Hello,

I've just started testing against version 21.01 on Mac:

`rawcooked --version
RAWcooked 21.01
`

and I receive this warning when using "--all":

`rawcooked --all input_dpx_files --output-name /output/path/outfile.mkv

Track 1:
  input_dpx_files_%08d.dpx
 (00000000 --> 00017693)
  DPX/Raw/RGB/10bit/FilledA/BE

Warning: non-conforming DPX Total image file size (x17694).
At least 1 file is not conform to specifications.

Do you want to continue despite warnings? `

Does "DPX Total image file size" refer to the file size on disk?  If so, all files appear to be the same size on disk: 

`14934016`

I'm glad to provide any additional info as needed.

Any help understanding this message would be appreciated.

**Comment by archisysio** [comment]
It appears that the warning is generated via the `--conch` switch. 

Testing against, `rawcooked --info --check --hash --coherency --check-padding --encode`, doesn't present the warning and encoding begins as expected.

**Comment by JeromeMartinez** [comment]
> Does "DPX Total image file size" refer to the file size on disk?

No.

> It appears that the warning is generated via the `--conch` switch.

Because it is a conformance issue: the file can be parsed (else the encoder would have rejected it even without `--conch`), no problem, but some internal stuff is not conform to specification.

Example of [trace](https://mediaarea.net/MediaTrace) of a DPX file:

```
000000 Generic section header (1664 bytes)
000000  File information (768 bytes)
000000   Magic number:                         SDPX
000004   Offset to image data:                 65536 (0x00010000)
000008   Version number of header format:      V2.0
000010   Total image file size:                5804032 (0x00589000)
000014   Ditto Key:                            0 (0x00000000)
000018   Generic section header length:        1664 (0x00000680)
00001C   Industry specific header length:      384 (0x00000180)
000020   User-defined header length:           512 (0x00000200)
000024   FileName:                             0000001.dpx
000088   Creation Date:                        2016:12:20:11:35:06:GMT
000294   Encryption key:                       4294967295 (0xFFFFFFFF)
000298   Reserved for future use:              (104 bytes)
[...]
```

Here, the value at offset 0x10 of your file should be same as the real file size (the byte size of my sample file is 5804032, so it matches), and the warning is there because it is not. It may be due to some extra (opaque) data after image data or a bad (= non conforming) DPX writer.

Or maybe our conformance checker is buggy, but I have doubts there and I can not check without a sample file.
