### ISSUE TITLE
[wish] add full path to rawcooked.1

### ISSUE THREAD

**Issue by retokromer** [MediaArea/RAWcooked#5]
In line https://github.com/MediaArea/RAWcooked/blob/master/Source/CLI/Main.cpp#L278 the full path to `rawcooked.1` should be given, in order to work by drag & dropping the file into the Terminal as well.

**Comment by retokromer** [comment]
I also have a doubt regarding `-slices 64`: why that high?

**Comment by JeromeMartinez** [comment]
>  why that high?

lot of different points of view on the count of slices.
e.g. for SD (350k pixels)  FFV1 says 4 slices mini (~100k/slice) and @dericed prefers 24 slices (15k/slice) in order to not lose too much content if a slice is corrupted vs a compression reduced by 2-4% (we tested on files from VIAA).
so for 4K (9M pixels) it would be between 90 and 600 slices per frame.

the arbitrary choice was a quick choice, more for testing multithreading capability of my decoder, as it does not support yet support of several frames at the same time. It will be changed to a value depending on the frame width/height, and will be modfifiable via an option.

Note that I plan to use AVX-512, so 32 slices per thread, so with a 8 core / 16 thread CPU, a throughtput of 1 multiplication per cycle (some CPU have 2 multiplications per cycle!) but a latency of 4 cycles, I need to feed the CPU with 2048 independent slices (similar number with GPUs), so having 4 frames of 512 slices for 4K content may be good.
I'll do a dedicated page about this debate soon.

**Comment by retokromer** [comment]
I made some tests a few years ago, before we have decided to embrace FFV1. The best results were when the number of slices equals the number of cores. Second best when `slices = n × cores` (`n ∈ ℕ`). That’s the reason why I asked.

**Comment by retokromer** [comment]
>the arbitrary choice was a quick choice, more for testing multithreading capability of my decoder, as it does not support yet support of several frames at the same time. It will be changed to a value depending on the frame width/height, and will be modfifiable via an option.

In mine this can be modified as well, and the suggested choice depends on the hardware on which it has been compiled. I guess, we have a similar approach.

**Comment by JeromeMartinez** [comment]
Implemented while working on https://github.com/MediaArea/RAWcooked/pull/12 (+ name is now "rawcooked.id=1", "1" will change in the future to the ID of the track when I implement the support of multiple tracks)
